title: "P[icture]log"
description: A log of pictures from my life
author: Kyrre Havik

# jekyll-paginate configuration
paginate: 5

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:year/:month/:title
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag

# RSS 2.0 can be used instead of Atom by uncommenting following two lines
#feed:
#  path: rss-feed.xml

# Customized settings
post_date_prefix: Written on
menu:
- name: Bikepacking
  url: bikepacking
- name: Japan
  url: japan
- name: About
  url: about
pagination:
  next_page: 'Newer'
  previous_page: 'Older'
